apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dapr-system
resources:
  - namespace.yaml
  - redis-menu-state-component.yaml
  - redis-users-state-component.yaml
  - rabbitmq-component.yaml
