apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: menu-state-store
  namespace: menu
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: redis-master.redis:6379
    - name: redisPassword
      value: ""
