apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: order-service
  namespace: restaurant-app
spec:
  releaseName: order-service
  chart:
    spec:
      chart: restaurant-app
      sourceRef:
        kind: HelmRepository
        name: restaurant-app
        namespace: flux-system
      version: "1.0"
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    menu-service:
      enabled: false
    users-service:
      enabled: false
    cache: redis-master.redis:6379
    image:
      tag: "main"
    ingress:
      enabled: true
    podAnnotations:
      dapr.io/enabled: "true"
      dapr.io/app-id: "order-service"
      dapr.io/app-port: "80"
